### ISSUE TITLE
Tutoriel simple en français

### ISSUE THREAD

**Issue by ydainna** [Omen-/dofus-key-finder#1]
salut.
tout d'abord merci pour ton tool
part contre j'aurais aimer s'avoir s(si possible) d'avoir un tuto d’installation et d'utilisation plus simple que se qui est sur github (plus compréhensible). Car pour être honnête je n'ais rien compris du tout (désoler si je suis débile haha) mais au moins ça aiderais surement pas que moi mais d'autres gens qui poseront surement la même question que moi.
merci

**Comment by arbll** [comment]
Hello,

On vas partir du principe que t'es sur windows, que tu sais ce qu'est MySQL et que tu as sur ton ordinateur un logiciel type wamp.

1. Télécharge le dernier exe [ici](https://github.com/Omen-/dofus-key-finder/releases)
2. Télécharge sur [ce site](http://www.swf-redirect.com/tools/tunnel/) la base de donnée des maps en cliquant sur "Télécharger les maps et triggers"
3. Importe dans ta base de donnée le fichier maps.sql téléchargé (le fichier est dans l'archive). Là tu risques d'avoir des problèmes car le fichier fait 100+MB et que ton installation de php ne va sûrement pas accepter son upload dans phpmyadmin. Pour y remédier il faut que tu : 
  + Trouve le dossier d'installation wamp (ou autre logiciels du type) et que tu trouve le fichier "mysql.exe". 
  + Copie ou déplace le fichier maps.sql dans ce dossier. 
  + Copie le chemin du dossier et ouvre une console puis tape `cd /d colle_le_chemin_ici` . 
  + Tape dans la console `mysql -u username -p database_name < maps.sql` en remplaçant username et database_name par ton username (probablement root) et le nom d'une BDD (tu peux en créer une dans l'interface de phpmyadmin).
4. Lance le tool depuis une console en tapant `findmapkey -db="username:password@/database_name" -maps=1000,1001` en remplaçant par ton username/password et par le nom de ta base.

Si tu bloques à une étape dis-moi avec quoi t'as du mal.

**Comment by ydainna** [comment]
Merci pour les précisions 
donc j'use pas PHPmyAdmin mais navicat, j'ai importer la table des maps.
le probléme quand je lance la cmd : `findmapkey -db="username:password@/database_name" -maps=1000,1001` cela me dit que la cmd n'est pas recconue, y a t-il quelque chose a faire d'autres en particulier ? l'exe que j'ai DL au debut je le met ou ? 
merci a toi et désoler pour toutes c'est questions

**Comment by arbll** [comment]
Fait un `cd /d chemin_vers_dossier_avec_findmapkey_exe` dans ta console et vu que t'es sur windows faut probablement écrire `findmapkey.exe -db="username:password@/database_name" -maps=1000,1001`

**Comment by ydainna** [comment]
super ça marche merci !
donc si je comprend bien la cmd : 

`findmapkey.exe -db="root:@/maps" -maps=1000,1001`

se qui correspond à : maps=1000,1001 en gros c'est la liste que l'ont veux cassé ?
sinon bah ça marche niquel le seul truc qui serai cool en effet comme tu l'a dit sur le sujet du forum serais de faire en sorte que ça update la db avec les infos recup.
merci

edit : certaines map ne son pas recconue part les commandes comme les maps : 12154 etc


panic: Map does not exist

goroutine 1 [running]:
main.findMapByID(0x2f86, 0xc047846000, 0x1eab, 0x1f6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/cmd/findmapkey/main.go:46 +0x13e
main.main()
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/cmd/findmapkey/main.go:27 +0x211

edit-2 : en faite je viens de remarquer que c'est à cause des doublons.

**Comment by arbll** [comment]
C'est à dire ? Y'a un bug du coup ou pas ?

Edit: Ok j'ai compris le problème

**Comment by ydainna** [comment]
bah oui je n'arrrive pas a faire certaines map comme dit 
ex: 12154,12166 etc

**Comment by arbll** [comment]
J'ai fix un bug : https://github.com/Omen-/dofus-key-finder/releases/tag/v0.3

Tu devrais plus avoir de `panic: Map does not exist`. La première map seras sélectionnée quand y'en a plusieurs

**Comment by ydainna** [comment]
d'accord je vais test ça merci

**Comment by arbll** [comment]
J'ai ajouté la gestion de plusieurs maps avec la même id : https://github.com/Omen-/dofus-key-finder/releases/tag/v0.4
Si tu peux tester aussi c'est cool

**Comment by ydainna** [comment]
okey je testerais merci

**Comment by ydainna** [comment]
part contre je viens de voir dans la db partagée que certaines dates sont pas a jour comparer au client 
(les maps dans le client)
